services:
  - type: worker
    name: chatsafari-bots
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: CHROME_DRIVER_PATH
        value: /usr/local/bin/chromedriver
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_RETRIES
        value: 3
      - key: RETRY_DELAY
        value: 5
